all:
  vars:
    node_app_name: polkastake
    node_binary_version: v0.9.39
    node_chain: polkadot
    node_user: polkadot
    node_binary: https://github.com/paritytech/polkadot/releases/download/{{ node_binary_version }}/polkadot
    node_binary_signature: https://github.com/paritytech/polkadot/releases/download/{{ node_binary_version }}/polkadot.asc
  children:
    fullnodes:
      vars:
      hosts:
        rofl:
          ansible_host: rofl.roflol.net
          node_role: full
        lol:
          ansible_host: lol.roflol.net
          node_role: full
