all:
  vars:
    node_app_name: polkastake
    node_binary_version: v0.9.39
    node_chain: westend
    node_user: polkadot
    node_binary: https://github.com/paritytech/polkadot/releases/download/{{ node_binary_version }}/polkadot
    node_binary_signature: https://github.com/paritytech/polkadot/releases/download/{{ node_binary_version }}/polkadot.asc
  children:
    fullnodes:
      vars:
      hosts:
        roflol-a:
          ansible_host: roflol-a.roflol.net
          node_role: full
        roflol-b:
          ansible_host: roflol-b.roflol.net
          node_role: full
